export interface Word {
  kana: string;      // Japanese writing (hiragana or katakana)
  romanji: string;   // Romanization (expected answer)
  meaning: string;   // English translation
}

// Hiragana-only words (~300 common Japanese words)
export const hiraganaWords: Word[] = [
  // Greetings & Common Phrases
  { kana: 'おはよう', romanji: 'ohayou', meaning: 'good morning' },
  { kana: 'こんにちは', romanji: 'konnichiwa', meaning: 'hello' },
  { kana: 'こんばんは', romanji: 'konbanwa', meaning: 'good evening' },
  { kana: 'ありがとう', romanji: 'arigatou', meaning: 'thank you' },
  { kana: 'さようなら', romanji: 'sayounara', meaning: 'goodbye' },
  { kana: 'すみません', romanji: 'sumimasen', meaning: 'excuse me, sorry' },
  { kana: 'ごめんなさい', romanji: 'gomennasai', meaning: 'I am sorry' },
  { kana: 'おやすみ', romanji: 'oyasumi', meaning: 'good night' },
  { kana: 'いただきます', romanji: 'itadakimasu', meaning: 'bon appetit (before eating)' },
  { kana: 'ごちそうさま', romanji: 'gochisousama', meaning: 'thank you for the meal' },

  // Common Verbs (dictionary form)
  { kana: 'たべる', romanji: 'taberu', meaning: 'to eat' },
  { kana: 'のむ', romanji: 'nomu', meaning: 'to drink' },
  { kana: 'みる', romanji: 'miru', meaning: 'to see, to watch' },
  { kana: 'きく', romanji: 'kiku', meaning: 'to listen, to hear' },
  { kana: 'はなす', romanji: 'hanasu', meaning: 'to speak' },
  { kana: 'よむ', romanji: 'yomu', meaning: 'to read' },
  { kana: 'かく', romanji: 'kaku', meaning: 'to write' },
  { kana: 'ある', romanji: 'aru', meaning: 'to exist (inanimate)' },
  { kana: 'いる', romanji: 'iru', meaning: 'to exist (animate)' },
  { kana: 'する', romanji: 'suru', meaning: 'to do' },
  { kana: 'いく', romanji: 'iku', meaning: 'to go' },
  { kana: 'くる', romanji: 'kuru', meaning: 'to come' },
  { kana: 'かえる', romanji: 'kaeru', meaning: 'to return home' },
  { kana: 'ねる', romanji: 'neru', meaning: 'to sleep' },
  { kana: 'おきる', romanji: 'okiru', meaning: 'to wake up' },
  { kana: 'あるく', romanji: 'aruku', meaning: 'to walk' },
  { kana: 'はしる', romanji: 'hashiru', meaning: 'to run' },
  { kana: 'とぶ', romanji: 'tobu', meaning: 'to fly, to jump' },
  { kana: 'およぐ', romanji: 'oyogu', meaning: 'to swim' },
  { kana: 'すわる', romanji: 'suwaru', meaning: 'to sit' },
  { kana: 'たつ', romanji: 'tatsu', meaning: 'to stand' },
  { kana: 'ねる', romanji: 'neru', meaning: 'to sleep' },
  { kana: 'あそぶ', romanji: 'asobu', meaning: 'to play' },
  { kana: 'はたらく', romanji: 'hataraku', meaning: 'to work' },
  { kana: 'べんきょうする', romanji: 'benkyousuru', meaning: 'to study' },
  { kana: 'おしえる', romanji: 'oshieru', meaning: 'to teach' },
  { kana: 'ならう', romanji: 'narau', meaning: 'to learn' },
  { kana: 'わかる', romanji: 'wakaru', meaning: 'to understand' },
  { kana: 'しる', romanji: 'shiru', meaning: 'to know' },
  { kana: 'おもう', romanji: 'omou', meaning: 'to think' },
  { kana: 'かんがえる', romanji: 'kangaeru', meaning: 'to consider' },
  { kana: 'わすれる', romanji: 'wasureru', meaning: 'to forget' },
  { kana: 'おぼえる', romanji: 'oboeru', meaning: 'to remember, to memorize' },
  { kana: 'あう', romanji: 'au', meaning: 'to meet' },
  { kana: 'あける', romanji: 'akeru', meaning: 'to open' },
  { kana: 'しめる', romanji: 'shimeru', meaning: 'to close' },
  { kana: 'かう', romanji: 'kau', meaning: 'to buy' },
  { kana: 'うる', romanji: 'uru', meaning: 'to sell' },
  { kana: 'あげる', romanji: 'ageru', meaning: 'to give' },
  { kana: 'もらう', romanji: 'morau', meaning: 'to receive' },
  { kana: 'つくる', romanji: 'tsukuru', meaning: 'to make' },
  { kana: 'きる', romanji: 'kiru', meaning: 'to cut' },
  { kana: 'きる', romanji: 'kiru', meaning: 'to wear' },
  { kana: 'ぬぐ', romanji: 'nugu', meaning: 'to take off (clothes)' },
  { kana: 'あらう', romanji: 'arau', meaning: 'to wash' },
  { kana: 'そうじする', romanji: 'soujisuru', meaning: 'to clean' },
  { kana: 'りょうりする', romanji: 'ryourisuru', meaning: 'to cook' },
  { kana: 'うたう', romanji: 'utau', meaning: 'to sing' },
  { kana: 'おどる', romanji: 'odoru', meaning: 'to dance' },
  { kana: 'やすむ', romanji: 'yasumu', meaning: 'to rest' },
  { kana: 'まつ', romanji: 'matsu', meaning: 'to wait' },
  { kana: 'とまる', romanji: 'tomaru', meaning: 'to stop' },
  { kana: 'はじまる', romanji: 'hajimaru', meaning: 'to begin' },
  { kana: 'おわる', romanji: 'owaru', meaning: 'to end' },
  { kana: 'いう', romanji: 'iu', meaning: 'to say' },
  { kana: 'よぶ', romanji: 'yobu', meaning: 'to call' },
  { kana: 'こたえる', romanji: 'kotaeru', meaning: 'to answer' },

  // Adjectives (い-adjectives)
  { kana: 'おおきい', romanji: 'ookii', meaning: 'big' },
  { kana: 'ちいさい', romanji: 'chiisai', meaning: 'small' },
  { kana: 'ながい', romanji: 'nagai', meaning: 'long' },
  { kana: 'みじかい', romanji: 'mijikai', meaning: 'short' },
  { kana: 'たかい', romanji: 'takai', meaning: 'tall, high, expensive' },
  { kana: 'ひくい', romanji: 'hikui', meaning: 'short (height), low' },
  { kana: 'ひろい', romanji: 'hiroi', meaning: 'wide, spacious' },
  { kana: 'せまい', romanji: 'semai', meaning: 'narrow' },
  { kana: 'ふとい', romanji: 'futoi', meaning: 'thick, fat' },
  { kana: 'ほそい', romanji: 'hosoi', meaning: 'thin, slender' },
  { kana: 'おもい', romanji: 'omoi', meaning: 'heavy' },
  { kana: 'かるい', romanji: 'karui', meaning: 'light (weight)' },
  { kana: 'つよい', romanji: 'tsuyoi', meaning: 'strong' },
  { kana: 'よわい', romanji: 'yowai', meaning: 'weak' },
  { kana: 'かたい', romanji: 'katai', meaning: 'hard' },
  { kana: 'やわらかい', romanji: 'yawarakai', meaning: 'soft' },
  { kana: 'いい', romanji: 'ii', meaning: 'good' },
  { kana: 'わるい', romanji: 'warui', meaning: 'bad' },
  { kana: 'あたらしい', romanji: 'atarashii', meaning: 'new' },
  { kana: 'ふるい', romanji: 'furui', meaning: 'old (thing)' },
  { kana: 'わかい', romanji: 'wakai', meaning: 'young' },
  { kana: 'あつい', romanji: 'atsui', meaning: 'hot' },
  { kana: 'さむい', romanji: 'samui', meaning: 'cold' },
  { kana: 'あたたかい', romanji: 'atatakai', meaning: 'warm' },
  { kana: 'すずしい', romanji: 'suzushii', meaning: 'cool' },
  { kana: 'あかるい', romanji: 'akarui', meaning: 'bright' },
  { kana: 'くらい', romanji: 'kurai', meaning: 'dark' },
  { kana: 'しずかな', romanji: 'shizukana', meaning: 'quiet' },
  { kana: 'うるさい', romanji: 'urusai', meaning: 'noisy' },
  { kana: 'はやい', romanji: 'hayai', meaning: 'fast, early' },
  { kana: 'おそい', romanji: 'osoi', meaning: 'slow, late' },
  { kana: 'ちかい', romanji: 'chikai', meaning: 'near' },
  { kana: 'とおい', romanji: 'tooi', meaning: 'far' },
  { kana: 'ふかい', romanji: 'fukai', meaning: 'deep' },
  { kana: 'あさい', romanji: 'asai', meaning: 'shallow' },
  { kana: 'たのしい', romanji: 'tanoshii', meaning: 'fun, enjoyable' },
  { kana: 'うれしい', romanji: 'ureshii', meaning: 'happy, glad' },
  { kana: 'かなしい', romanji: 'kanashii', meaning: 'sad' },
  { kana: 'さびしい', romanji: 'sabishii', meaning: 'lonely' },
  { kana: 'うつくしい', romanji: 'utsukushii', meaning: 'beautiful' },
  { kana: 'きれいな', romanji: 'kireina', meaning: 'pretty, clean' },
  { kana: 'きたない', romanji: 'kitanai', meaning: 'dirty' },
  { kana: 'おいしい', romanji: 'oishii', meaning: 'delicious' },
  { kana: 'まずい', romanji: 'mazui', meaning: 'unappetizing, bad-tasting' },
  { kana: 'あまい', romanji: 'amai', meaning: 'sweet' },
  { kana: 'からい', romanji: 'karai', meaning: 'spicy, salty' },
  { kana: 'すっぱい', romanji: 'suppai', meaning: 'sour' },
  { kana: 'にがい', romanji: 'nigai', meaning: 'bitter' },
  { kana: 'むずかしい', romanji: 'muzukashii', meaning: 'difficult' },
  { kana: 'やさしい', romanji: 'yasashii', meaning: 'easy, kind' },
  { kana: 'おもしろい', romanji: 'omoshiroi', meaning: 'interesting' },
  { kana: 'つまらない', romanji: 'tsumaranai', meaning: 'boring' },
  { kana: 'すごい', romanji: 'sugoi', meaning: 'amazing, terrible' },
  { kana: 'こわい', romanji: 'kowai', meaning: 'scary' },

  // Common Nouns
  { kana: 'ひと', romanji: 'hito', meaning: 'person' },
  { kana: 'ひ', romanji: 'hi', meaning: 'day, sun' },
  { kana: 'とき', romanji: 'toki', meaning: 'time' },
  { kana: 'もの', romanji: 'mono', meaning: 'thing' },
  { kana: 'こと', romanji: 'koto', meaning: 'matter, thing (abstract)' },
  { kana: 'ところ', romanji: 'tokoro', meaning: 'place' },
  { kana: 'いえ', romanji: 'ie', meaning: 'house' },
  { kana: 'うち', romanji: 'uchi', meaning: 'home, house' },
  { kana: 'へや', romanji: 'heya', meaning: 'room' },
  { kana: 'みせ', romanji: 'mise', meaning: 'shop, store' },
  { kana: 'まち', romanji: 'machi', meaning: 'town' },
  { kana: 'くに', romanji: 'kuni', meaning: 'country' },
  { kana: 'みち', romanji: 'michi', meaning: 'road, path' },
  { kana: 'やま', romanji: 'yama', meaning: 'mountain' },
  { kana: 'かわ', romanji: 'kawa', meaning: 'river' },
  { kana: 'うみ', romanji: 'umi', meaning: 'sea, ocean' },
  { kana: 'そら', romanji: 'sora', meaning: 'sky' },
  { kana: 'き', romanji: 'ki', meaning: 'tree' },
  { kana: 'はな', romanji: 'hana', meaning: 'flower' },
  { kana: 'くさ', romanji: 'kusa', meaning: 'grass' },
  { kana: 'いし', romanji: 'ishi', meaning: 'stone' },
  { kana: 'みず', romanji: 'mizu', meaning: 'water' },
  { kana: 'ひ', romanji: 'hi', meaning: 'fire' },
  { kana: 'かぜ', romanji: 'kaze', meaning: 'wind' },
  { kana: 'あめ', romanji: 'ame', meaning: 'rain' },
  { kana: 'ゆき', romanji: 'yuki', meaning: 'snow' },
  { kana: 'くも', romanji: 'kumo', meaning: 'cloud' },
  { kana: 'つき', romanji: 'tsuki', meaning: 'moon' },
  { kana: 'ほし', romanji: 'hoshi', meaning: 'star' },
  { kana: 'あさ', romanji: 'asa', meaning: 'morning' },
  { kana: 'ひる', romanji: 'hiru', meaning: 'daytime, noon' },
  { kana: 'よる', romanji: 'yoru', meaning: 'night' },
  { kana: 'ゆうがた', romanji: 'yuugata', meaning: 'evening' },
  { kana: 'きのう', romanji: 'kinou', meaning: 'yesterday' },
  { kana: 'きょう', romanji: 'kyou', meaning: 'today' },
  { kana: 'あした', romanji: 'ashita', meaning: 'tomorrow' },
  { kana: 'あさって', romanji: 'asatte', meaning: 'day after tomorrow' },
  { kana: 'まいにち', romanji: 'mainichi', meaning: 'every day' },
  { kana: 'まいあさ', romanji: 'maiasa', meaning: 'every morning' },
  { kana: 'まいばん', romanji: 'maiban', meaning: 'every evening' },

  // Animals
  { kana: 'いぬ', romanji: 'inu', meaning: 'dog' },
  { kana: 'ねこ', romanji: 'neko', meaning: 'cat' },
  { kana: 'とり', romanji: 'tori', meaning: 'bird' },
  { kana: 'さかな', romanji: 'sakana', meaning: 'fish' },
  { kana: 'うま', romanji: 'uma', meaning: 'horse' },
  { kana: 'うし', romanji: 'ushi', meaning: 'cow' },
  { kana: 'ぶた', romanji: 'buta', meaning: 'pig' },
  { kana: 'ひつじ', romanji: 'hitsuji', meaning: 'sheep' },
  { kana: 'やぎ', romanji: 'yagi', meaning: 'goat' },
  { kana: 'にわとり', romanji: 'niwatori', meaning: 'chicken' },
  { kana: 'あひる', romanji: 'ahiru', meaning: 'duck' },
  { kana: 'うさぎ', romanji: 'usagi', meaning: 'rabbit' },
  { kana: 'ねずみ', romanji: 'nezumi', meaning: 'mouse, rat' },
  { kana: 'さる', romanji: 'saru', meaning: 'monkey' },
  { kana: 'くま', romanji: 'kuma', meaning: 'bear' },
  { kana: 'きつね', romanji: 'kitsune', meaning: 'fox' },
  { kana: 'しか', romanji: 'shika', meaning: 'deer' },
  { kana: 'かえる', romanji: 'kaeru', meaning: 'frog' },
  { kana: 'へび', romanji: 'hebi', meaning: 'snake' },
  { kana: 'かめ', romanji: 'kame', meaning: 'turtle' },
  { kana: 'むし', romanji: 'mushi', meaning: 'insect' },
  { kana: 'ちょう', romanji: 'chou', meaning: 'butterfly' },
  { kana: 'あり', romanji: 'ari', meaning: 'ant' },
  { kana: 'はち', romanji: 'hachi', meaning: 'bee' },
  { kana: 'くも', romanji: 'kumo', meaning: 'spider' },

  // Family & People
  { kana: 'かぞく', romanji: 'kazoku', meaning: 'family' },
  { kana: 'ちち', romanji: 'chichi', meaning: 'father (own)' },
  { kana: 'はは', romanji: 'haha', meaning: 'mother (own)' },
  { kana: 'あに', romanji: 'ani', meaning: 'older brother (own)' },
  { kana: 'あね', romanji: 'ane', meaning: 'older sister (own)' },
  { kana: 'おとうと', romanji: 'otouto', meaning: 'younger brother' },
  { kana: 'いもうと', romanji: 'imouto', meaning: 'younger sister' },
  { kana: 'おとこ', romanji: 'otoko', meaning: 'man, male' },
  { kana: 'おんな', romanji: 'onna', meaning: 'woman, female' },
  { kana: 'こども', romanji: 'kodomo', meaning: 'child' },
  { kana: 'あかちゃん', romanji: 'akachan', meaning: 'baby' },
  { kana: 'おとな', romanji: 'otona', meaning: 'adult' },
  { kana: 'おとこのこ', romanji: 'otokonoko', meaning: 'boy' },
  { kana: 'おんなのこ', romanji: 'onnanoko', meaning: 'girl' },
  { kana: 'ともだち', romanji: 'tomodachi', meaning: 'friend' },
  { kana: 'せんせい', romanji: 'sensei', meaning: 'teacher' },
  { kana: 'がくせい', romanji: 'gakusei', meaning: 'student' },
  { kana: 'いしゃ', romanji: 'isha', meaning: 'doctor' },

  // Body Parts
  { kana: 'からだ', romanji: 'karada', meaning: 'body' },
  { kana: 'あたま', romanji: 'atama', meaning: 'head' },
  { kana: 'かお', romanji: 'kao', meaning: 'face' },
  { kana: 'め', romanji: 'me', meaning: 'eye' },
  { kana: 'みみ', romanji: 'mimi', meaning: 'ear' },
  { kana: 'はな', romanji: 'hana', meaning: 'nose' },
  { kana: 'くち', romanji: 'kuchi', meaning: 'mouth' },
  { kana: 'は', romanji: 'ha', meaning: 'tooth' },
  { kana: 'した', romanji: 'shita', meaning: 'tongue' },
  { kana: 'くび', romanji: 'kubi', meaning: 'neck' },
  { kana: 'かた', romanji: 'kata', meaning: 'shoulder' },
  { kana: 'うで', romanji: 'ude', meaning: 'arm' },
  { kana: 'て', romanji: 'te', meaning: 'hand' },
  { kana: 'ゆび', romanji: 'yubi', meaning: 'finger' },
  { kana: 'あし', romanji: 'ashi', meaning: 'leg, foot' },
  { kana: 'ひざ', romanji: 'hiza', meaning: 'knee' },
  { kana: 'せなか', romanji: 'senaka', meaning: 'back' },
  { kana: 'むね', romanji: 'mune', meaning: 'chest' },
  { kana: 'おなか', romanji: 'onaka', meaning: 'stomach' },
  { kana: 'こし', romanji: 'koshi', meaning: 'hip, waist, lower back' },
  { kana: 'かみ', romanji: 'kami', meaning: 'hair' },
  { kana: 'ほね', romanji: 'hone', meaning: 'bone' },
  { kana: 'ち', romanji: 'chi', meaning: 'blood' },
  { kana: 'こころ', romanji: 'kokoro', meaning: 'heart, mind' },

  // Food & Meals
  { kana: 'ごはん', romanji: 'gohan', meaning: 'rice, meal' },
  { kana: 'あさごはん', romanji: 'asagohan', meaning: 'breakfast' },
  { kana: 'ひるごはん', romanji: 'hirugohan', meaning: 'lunch' },
  { kana: 'ばんごはん', romanji: 'bangohan', meaning: 'dinner' },
  { kana: 'みず', romanji: 'mizu', meaning: 'water' },
  { kana: 'おちゃ', romanji: 'ocha', meaning: 'tea' },
  { kana: 'さけ', romanji: 'sake', meaning: 'alcohol, sake' },
  { kana: 'たまご', romanji: 'tamago', meaning: 'egg' },
  { kana: 'にく', romanji: 'niku', meaning: 'meat' },
  { kana: 'やさい', romanji: 'yasai', meaning: 'vegetable' },
  { kana: 'くだもの', romanji: 'kudamono', meaning: 'fruit' },
  { kana: 'しお', romanji: 'shio', meaning: 'salt' },
  { kana: 'さとう', romanji: 'satou', meaning: 'sugar' },

  // Directions & Locations
  { kana: 'うえ', romanji: 'ue', meaning: 'up, above' },
  { kana: 'した', romanji: 'shita', meaning: 'down, below' },
  { kana: 'まえ', romanji: 'mae', meaning: 'front' },
  { kana: 'うしろ', romanji: 'ushiro', meaning: 'behind, back' },
  { kana: 'みぎ', romanji: 'migi', meaning: 'right' },
  { kana: 'ひだり', romanji: 'hidari', meaning: 'left' },
  { kana: 'なか', romanji: 'naka', meaning: 'inside' },
  { kana: 'そと', romanji: 'soto', meaning: 'outside' },
  { kana: 'となり', romanji: 'tonari', meaning: 'next to' },
  { kana: 'あいだ', romanji: 'aida', meaning: 'between' },
  { kana: 'ちかく', romanji: 'chikaku', meaning: 'near' },
  { kana: 'とおく', romanji: 'tooku', meaning: 'far away' },
  { kana: 'ここ', romanji: 'koko', meaning: 'here' },
  { kana: 'そこ', romanji: 'soko', meaning: 'there' },
  { kana: 'あそこ', romanji: 'asoko', meaning: 'over there' },
  { kana: 'どこ', romanji: 'doko', meaning: 'where' },
  { kana: 'こっち', romanji: 'kocchi', meaning: 'this way' },
  { kana: 'そっち', romanji: 'socchi', meaning: 'that way' },
  { kana: 'あっち', romanji: 'acchi', meaning: 'that way (over there)' },
  { kana: 'どっち', romanji: 'docchi', meaning: 'which way' },

  // Demonstratives
  { kana: 'これ', romanji: 'kore', meaning: 'this' },
  { kana: 'それ', romanji: 'sore', meaning: 'that' },
  { kana: 'あれ', romanji: 'are', meaning: 'that (over there)' },
  { kana: 'どれ', romanji: 'dore', meaning: 'which' },
  { kana: 'この', romanji: 'kono', meaning: 'this (before noun)' },
  { kana: 'その', romanji: 'sono', meaning: 'that (before noun)' },
  { kana: 'あの', romanji: 'ano', meaning: 'that (before noun)' },
  { kana: 'どの', romanji: 'dono', meaning: 'which (before noun)' },

  // Question Words & Basic Grammar
  { kana: 'なに', romanji: 'nani', meaning: 'what' },
  { kana: 'なん', romanji: 'nan', meaning: 'what' },
  { kana: 'だれ', romanji: 'dare', meaning: 'who' },
  { kana: 'いつ', romanji: 'itsu', meaning: 'when' },
  { kana: 'どこ', romanji: 'doko', meaning: 'where' },
  { kana: 'なぜ', romanji: 'naze', meaning: 'why' },
  { kana: 'どう', romanji: 'dou', meaning: 'how' },
  { kana: 'どんな', romanji: 'donna', meaning: 'what kind of' },
  { kana: 'いくつ', romanji: 'ikutsu', meaning: 'how many' },
  { kana: 'いくら', romanji: 'ikura', meaning: 'how much' },

  // Colors
  { kana: 'あか', romanji: 'aka', meaning: 'red' },
  { kana: 'あお', romanji: 'ao', meaning: 'blue' },
  { kana: 'きいろ', romanji: 'kiiro', meaning: 'yellow' },
  { kana: 'みどり', romanji: 'midori', meaning: 'green' },
  { kana: 'しろ', romanji: 'shiro', meaning: 'white' },
  { kana: 'くろ', romanji: 'kuro', meaning: 'black' },
  { kana: 'ちゃいろ', romanji: 'chairo', meaning: 'brown' },

  // Abstract Concepts
  { kana: 'こころ', romanji: 'kokoro', meaning: 'heart, spirit' },
  { kana: 'いのち', romanji: 'inochi', meaning: 'life' },
  { kana: 'ゆめ', romanji: 'yume', meaning: 'dream' },
  { kana: 'ちから', romanji: 'chikara', meaning: 'power, strength' },
  { kana: 'こえ', romanji: 'koe', meaning: 'voice' },
  { kana: 'おと', romanji: 'oto', meaning: 'sound' },
  { kana: 'はなし', romanji: 'hanashi', meaning: 'talk, story' },
  { kana: 'ことば', romanji: 'kotoba', meaning: 'word, language' },
  { kana: 'なまえ', romanji: 'namae', meaning: 'name' },
  { kana: 'かず', romanji: 'kazu', meaning: 'number' },
  { kana: 'いろ', romanji: 'iro', meaning: 'color' },
  { kana: 'かたち', romanji: 'katachi', meaning: 'shape, form' },
];

// Katakana-only words (~300 common loanwords)
export const katakanaWords: Word[] = [
  // Drinks
  { kana: 'コーヒー', romanji: 'koohii', meaning: 'coffee' },
  { kana: 'ティー', romanji: 'tii', meaning: 'tea (western)' },
  { kana: 'ビール', romanji: 'biiru', meaning: 'beer' },
  { kana: 'ワイン', romanji: 'wain', meaning: 'wine' },
  { kana: 'ジュース', romanji: 'juusu', meaning: 'juice' },
  { kana: 'コーラ', romanji: 'koora', meaning: 'cola' },
  { kana: 'ソーダ', romanji: 'sooda', meaning: 'soda' },
  { kana: 'ミルク', romanji: 'miruku', meaning: 'milk' },
  { kana: 'カクテル', romanji: 'kakuteru', meaning: 'cocktail' },
  { kana: 'ウイスキー', romanji: 'uisukii', meaning: 'whiskey' },
  { kana: 'ウオッカ', romanji: 'uokka', meaning: 'vodka' },
  { kana: 'シャンパン', romanji: 'shanpan', meaning: 'champagne' },
  { kana: 'ラテ', romanji: 'rate', meaning: 'latte' },
  { kana: 'エスプレッソ', romanji: 'esupuresso', meaning: 'espresso' },
  { kana: 'カプチーノ', romanji: 'kapuchiino', meaning: 'cappuccino' },
  { kana: 'ココア', romanji: 'kokoa', meaning: 'cocoa, hot chocolate' },
  { kana: 'スムージー', romanji: 'sumuujii', meaning: 'smoothie' },

  // Food
  { kana: 'ケーキ', romanji: 'keeki', meaning: 'cake' },
  { kana: 'アイスクリーム', romanji: 'aisukuriimu', meaning: 'ice cream' },
  { kana: 'チョコレート', romanji: 'chokoreeto', meaning: 'chocolate' },
  { kana: 'クッキー', romanji: 'kukkii', meaning: 'cookie' },
  { kana: 'キャンディー', romanji: 'kyandii', meaning: 'candy' },
  { kana: 'チーズ', romanji: 'chiizu', meaning: 'cheese' },
  { kana: 'バター', romanji: 'bataa', meaning: 'butter' },
  { kana: 'ヨーグルト', romanji: 'yooguruto', meaning: 'yogurt' },
  { kana: 'ピザ', romanji: 'piza', meaning: 'pizza' },
  { kana: 'パスタ', romanji: 'pasuta', meaning: 'pasta' },
  { kana: 'スパゲッティ', romanji: 'supagetti', meaning: 'spaghetti' },
  { kana: 'サラダ', romanji: 'sarada', meaning: 'salad' },
  { kana: 'サンドイッチ', romanji: 'sandoicchi', meaning: 'sandwich' },
  { kana: 'ハンバーガー', romanji: 'hanbaagaa', meaning: 'hamburger' },
  { kana: 'ホットドッグ', romanji: 'hottodoggu', meaning: 'hot dog' },
  { kana: 'ステーキ', romanji: 'suteeki', meaning: 'steak' },
  { kana: 'ベーコン', romanji: 'beekon', meaning: 'bacon' },
  { kana: 'ソーセージ', romanji: 'sooseej', meaning: 'sausage' },
  { kana: 'トースト', romanji: 'toosuto', meaning: 'toast' },
  { kana: 'ジャム', romanji: 'jamu', meaning: 'jam' },
  { kana: 'ハチミツ', romanji: 'hachimitsu', meaning: 'honey' },
  { kana: 'ソース', romanji: 'soosu', meaning: 'sauce' },
  { kana: 'ケチャップ', romanji: 'kechappu', meaning: 'ketchup' },
  { kana: 'マヨネーズ', romanji: 'mayoneezu', meaning: 'mayonnaise' },
  { kana: 'カレー', romanji: 'karee', meaning: 'curry' },
  { kana: 'スープ', romanji: 'suupu', meaning: 'soup' },
  { kana: 'クリーム', romanji: 'kuriimu', meaning: 'cream' },
  { kana: 'プディング', romanji: 'pudingu', meaning: 'pudding' },
  { kana: 'パイ', romanji: 'pai', meaning: 'pie' },
  { kana: 'タルト', romanji: 'taruto', meaning: 'tart' },
  { kana: 'パフェ', romanji: 'pafe', meaning: 'parfait' },
  { kana: 'パンケーキ', romanji: 'pankeeki', meaning: 'pancake' },
  { kana: 'ワッフル', romanji: 'waffuru', meaning: 'waffle' },
  { kana: 'クロワッサン', romanji: 'kurowassan', meaning: 'croissant' },
  { kana: 'ベーグル', romanji: 'beeguru', meaning: 'bagel' },
  { kana: 'マフィン', romanji: 'mafin', meaning: 'muffin' },
  { kana: 'ドーナツ', romanji: 'doonatsu', meaning: 'donut' },
  { kana: 'ポップコーン', romanji: 'poppukoon', meaning: 'popcorn' },
  { kana: 'チップス', romanji: 'chippusu', meaning: 'chips' },
  { kana: 'フライドポテト', romanji: 'furaidopoteto', meaning: 'french fries' },
  { kana: 'ナゲット', romanji: 'nagetto', meaning: 'nugget' },
  { kana: 'オムレツ', romanji: 'omuretsu', meaning: 'omelet' },

  // Technology & Devices
  { kana: 'コンピューター', romanji: 'konpyuutaa', meaning: 'computer' },
  { kana: 'パソコン', romanji: 'pasokon', meaning: 'PC, personal computer' },
  { kana: 'インターネット', romanji: 'intaanetto', meaning: 'internet' },
  { kana: 'メール', romanji: 'meeru', meaning: 'email' },
  { kana: 'スマホ', romanji: 'sumaho', meaning: 'smartphone' },
  { kana: 'スマートフォン', romanji: 'sumaatofon', meaning: 'smartphone' },
  { kana: 'タブレット', romanji: 'taburetto', meaning: 'tablet' },
  { kana: 'ノートパソコン', romanji: 'nootopasokon', meaning: 'laptop' },
  { kana: 'キーボード', romanji: 'kiiboodo', meaning: 'keyboard' },
  { kana: 'マウス', romanji: 'mausu', meaning: 'mouse' },
  { kana: 'モニター', romanji: 'monitaa', meaning: 'monitor' },
  { kana: 'スクリーン', romanji: 'sukuriin', meaning: 'screen' },
  { kana: 'プリンター', romanji: 'purintaa', meaning: 'printer' },
  { kana: 'スキャナー', romanji: 'sukyanaa', meaning: 'scanner' },
  { kana: 'カメラ', romanji: 'kamera', meaning: 'camera' },
  { kana: 'ビデオ', romanji: 'bideo', meaning: 'video' },
  { kana: 'ソフトウェア', romanji: 'sofutowea', meaning: 'software' },
  { kana: 'ハードウェア', romanji: 'haadowea', meaning: 'hardware' },
  { kana: 'データ', romanji: 'deeta', meaning: 'data' },
  { kana: 'ファイル', romanji: 'fairu', meaning: 'file' },
  { kana: 'フォルダ', romanji: 'foruda', meaning: 'folder' },
  { kana: 'アプリ', romanji: 'apuri', meaning: 'app, application' },
  { kana: 'プログラム', romanji: 'puroguramu', meaning: 'program' },
  { kana: 'システム', romanji: 'shisutemu', meaning: 'system' },
  { kana: 'ネットワーク', romanji: 'nettowaaku', meaning: 'network' },
  { kana: 'サーバー', romanji: 'saabaa', meaning: 'server' },
  { kana: 'ルーター', romanji: 'ruutaa', meaning: 'router' },
  { kana: 'ケーブル', romanji: 'keeburu', meaning: 'cable' },
  { kana: 'チャージャー', romanji: 'chaajaa', meaning: 'charger' },
  { kana: 'バッテリー', romanji: 'batterii', meaning: 'battery' },
  { kana: 'ボタン', romanji: 'botan', meaning: 'button' },
  { kana: 'ウェブサイト', romanji: 'webusaito', meaning: 'website' },
  { kana: 'ブログ', romanji: 'burogu', meaning: 'blog' },
  { kana: 'ダウンロード', romanji: 'daunroodo', meaning: 'download' },
  { kana: 'アップロード', romanji: 'appuroodo', meaning: 'upload' },
  { kana: 'リンク', romanji: 'rinku', meaning: 'link' },
  { kana: 'クリック', romanji: 'kurikku', meaning: 'click' },

  // Entertainment & Media
  { kana: 'ゲーム', romanji: 'geemu', meaning: 'game' },
  { kana: 'ビデオゲーム', romanji: 'bideogeemu', meaning: 'video game' },
  { kana: 'アニメ', romanji: 'anime', meaning: 'animation, anime' },
  { kana: 'テレビ', romanji: 'terebi', meaning: 'television, TV' },
  { kana: 'ラジオ', romanji: 'rajio', meaning: 'radio' },
  { kana: 'ムービー', romanji: 'muubii', meaning: 'movie' },
  { kana: 'フィルム', romanji: 'firumu', meaning: 'film' },
  { kana: 'ドラマ', romanji: 'dorama', meaning: 'drama' },
  { kana: 'コメディ', romanji: 'komedi', meaning: 'comedy' },
  { kana: 'ミュージック', romanji: 'myuujikku', meaning: 'music' },
  { kana: 'コンサート', romanji: 'konsaato', meaning: 'concert' },
  { kana: 'ショー', romanji: 'shoo', meaning: 'show' },
  { kana: 'ニュース', romanji: 'nyuusu', meaning: 'news' },
  { kana: 'チャンネル', romanji: 'channeru', meaning: 'channel' },
  { kana: 'ポッドキャスト', romanji: 'poddokyasuto', meaning: 'podcast' },
  { kana: 'ストリーミング', romanji: 'sutoriimingu', meaning: 'streaming' },
  { kana: 'ディスク', romanji: 'disuku', meaning: 'disc (CD/DVD)' },
  { kana: 'レコード', romanji: 'rekoodo', meaning: 'record' },
  { kana: 'カセット', romanji: 'kasetto', meaning: 'cassette' },
  { kana: 'ヘッドホン', romanji: 'heddohon', meaning: 'headphones' },
  { kana: 'スピーカー', romanji: 'supiikaa', meaning: 'speaker' },
  { kana: 'マイク', romanji: 'maiku', meaning: 'microphone' },

  // Sports & Fitness
  { kana: 'スポーツ', romanji: 'supootsu', meaning: 'sports' },
  { kana: 'テニス', romanji: 'tenisu', meaning: 'tennis' },
  { kana: 'サッカー', romanji: 'sakkaa', meaning: 'soccer' },
  { kana: 'フットボール', romanji: 'futtobooru', meaning: 'football' },
  { kana: 'バスケットボール', romanji: 'basukettobooru', meaning: 'basketball' },
  { kana: 'ベースボール', romanji: 'beesubooru', meaning: 'baseball' },
  { kana: 'バレーボール', romanji: 'bareebooru', meaning: 'volleyball' },
  { kana: 'ゴルフ', romanji: 'gorufu', meaning: 'golf' },
  { kana: 'スキー', romanji: 'sukii', meaning: 'skiing' },
  { kana: 'スケート', romanji: 'sukeeto', meaning: 'skating' },
  { kana: 'スイミング', romanji: 'suimingu', meaning: 'swimming' },
  { kana: 'サーフィン', romanji: 'saafin', meaning: 'surfing' },
  { kana: 'ボクシング', romanji: 'bokushingu', meaning: 'boxing' },
  { kana: 'ランニング', romanji: 'ranningu', meaning: 'running' },
  { kana: 'マラソン', romanji: 'marason', meaning: 'marathon' },
  { kana: 'トレーニング', romanji: 'toreeningu', meaning: 'training' },
  { kana: 'エクササイズ', romanji: 'ekusasaizu', meaning: 'exercise' },
  { kana: 'ジム', romanji: 'jimu', meaning: 'gym' },
  { kana: 'フィットネス', romanji: 'fittonesu', meaning: 'fitness' },
  { kana: 'ヨガ', romanji: 'yoga', meaning: 'yoga' },
  { kana: 'エアロビクス', romanji: 'earobikusu', meaning: 'aerobics' },
  { kana: 'チーム', romanji: 'chiimu', meaning: 'team' },
  { kana: 'マッチ', romanji: 'macchi', meaning: 'match' },
  { kana: 'トーナメント', romanji: 'toonamento', meaning: 'tournament' },
  { kana: 'チャンピオン', romanji: 'chanpion', meaning: 'champion' },
  { kana: 'メダル', romanji: 'medaru', meaning: 'medal' },
  { kana: 'トロフィー', romanji: 'torofii', meaning: 'trophy' },
  { kana: 'コーチ', romanji: 'koochi', meaning: 'coach' },

  // Transportation
  { kana: 'バス', romanji: 'basu', meaning: 'bus' },
  { kana: 'タクシー', romanji: 'takushii', meaning: 'taxi' },
  { kana: 'トラック', romanji: 'torakku', meaning: 'truck' },
  { kana: 'カー', romanji: 'kaa', meaning: 'car' },
  { kana: 'モーターサイクル', romanji: 'mootaasaikuru', meaning: 'motorcycle' },
  { kana: 'バイク', romanji: 'baiku', meaning: 'bike, motorcycle' },
  { kana: 'サイクル', romanji: 'saikuru', meaning: 'bicycle' },
  { kana: 'トレイン', romanji: 'torein', meaning: 'train' },
  { kana: 'エアプレーン', romanji: 'eapureen', meaning: 'airplane' },
  { kana: 'ヘリコプター', romanji: 'herikoputaa', meaning: 'helicopter' },
  { kana: 'ボート', romanji: 'booto', meaning: 'boat' },
  { kana: 'シップ', romanji: 'shippu', meaning: 'ship' },
  { kana: 'フェリー', romanji: 'ferii', meaning: 'ferry' },
  { kana: 'ロケット', romanji: 'roketto', meaning: 'rocket' },
  { kana: 'エンジン', romanji: 'enjin', meaning: 'engine' },
  { kana: 'タイヤ', romanji: 'taiya', meaning: 'tire' },
  { kana: 'ホイール', romanji: 'hoiiru', meaning: 'wheel' },
  { kana: 'ブレーキ', romanji: 'bureeki', meaning: 'brake' },
  { kana: 'ガソリン', romanji: 'gasorin', meaning: 'gasoline' },
  { kana: 'ディーゼル', romanji: 'diizeru', meaning: 'diesel' },

  // Places & Buildings
  { kana: 'ホテル', romanji: 'hoteru', meaning: 'hotel' },
  { kana: 'モーテル', romanji: 'mooteru', meaning: 'motel' },
  { kana: 'レストラン', romanji: 'resutoran', meaning: 'restaurant' },
  { kana: 'カフェ', romanji: 'kafe', meaning: 'cafe' },
  { kana: 'バー', romanji: 'baa', meaning: 'bar' },
  { kana: 'パブ', romanji: 'pabu', meaning: 'pub' },
  { kana: 'クラブ', romanji: 'kurabu', meaning: 'club' },
  { kana: 'ディスコ', romanji: 'disuko', meaning: 'disco' },
  { kana: 'カジノ', romanji: 'kajino', meaning: 'casino' },
  { kana: 'モール', romanji: 'mooru', meaning: 'mall' },
  { kana: 'スーパーマーケット', romanji: 'suupaamaaketto', meaning: 'supermarket' },
  { kana: 'ストア', romanji: 'sutoa', meaning: 'store' },
  { kana: 'ショップ', romanji: 'shoppu', meaning: 'shop' },
  { kana: 'ブティック', romanji: 'butikku', meaning: 'boutique' },
  { kana: 'パーク', romanji: 'paaku', meaning: 'park' },
  { kana: 'スタジアム', romanji: 'sutajiamu', meaning: 'stadium' },
  { kana: 'シアター', romanji: 'shiataa', meaning: 'theater' },
  { kana: 'シネマ', romanji: 'shinema', meaning: 'cinema' },
  { kana: 'ミュージアム', romanji: 'myuujiamu', meaning: 'museum' },
  { kana: 'ギャラリー', romanji: 'gyararii', meaning: 'gallery' },
  { kana: 'ロビー', romanji: 'robii', meaning: 'lobby' },
  { kana: 'エレベーター', romanji: 'erebeetaa', meaning: 'elevator' },
  { kana: 'エスカレーター', romanji: 'esukareetaa', meaning: 'escalator' },

  // Office & School Supplies
  { kana: 'オフィス', romanji: 'ofisu', meaning: 'office' },
  { kana: 'デスク', romanji: 'desuku', meaning: 'desk' },
  { kana: 'テーブル', romanji: 'teeburu', meaning: 'table' },
  { kana: 'チェア', romanji: 'chea', meaning: 'chair' },
  { kana: 'ソファ', romanji: 'sofa', meaning: 'sofa' },
  { kana: 'ベッド', romanji: 'beddo', meaning: 'bed' },
  { kana: 'シェルフ', romanji: 'sherufu', meaning: 'shelf' },
  { kana: 'ペン', romanji: 'pen', meaning: 'pen' },
  { kana: 'ペンシル', romanji: 'penshiru', meaning: 'pencil' },
  { kana: 'マーカー', romanji: 'maakaa', meaning: 'marker' },
  { kana: 'イレーサー', romanji: 'ireesaa', meaning: 'eraser' },
  { kana: 'ノート', romanji: 'nooto', meaning: 'notebook' },
  { kana: 'ノートブック', romanji: 'nootobukku', meaning: 'notebook' },
  { kana: 'フォルダー', romanji: 'forudaa', meaning: 'folder' },
  { kana: 'ステープラー', romanji: 'suteepu raa', meaning: 'stapler' },
  { kana: 'クリップ', romanji: 'kurippu', meaning: 'clip' },
  { kana: 'テープ', romanji: 'teepu', meaning: 'tape' },
  { kana: 'カレンダー', romanji: 'karendaa', meaning: 'calendar' },
  { kana: 'スケジュール', romanji: 'sukejuuru', meaning: 'schedule' },
  { kana: 'メモ', romanji: 'memo', meaning: 'memo' },
  { kana: 'レポート', romanji: 'repooto', meaning: 'report' },
  { kana: 'ミーティング', romanji: 'miitingu', meaning: 'meeting' },
  { kana: 'プレゼンテーション', romanji: 'purezenteshon', meaning: 'presentation' },
  { kana: 'セミナー', romanji: 'seminaa', meaning: 'seminar' },
  { kana: 'プロジェクト', romanji: 'purojekuto', meaning: 'project' },

  // Clothing & Fashion
  { kana: 'シャツ', romanji: 'shatsu', meaning: 'shirt' },
  { kana: 'ティーシャツ', romanji: 'tiishatsu', meaning: 'T-shirt' },
  { kana: 'ブラウス', romanji: 'burausu', meaning: 'blouse' },
  { kana: 'セーター', romanji: 'seetaa', meaning: 'sweater' },
  { kana: 'ジャケット', romanji: 'jaketto', meaning: 'jacket' },
  { kana: 'コート', romanji: 'kooto', meaning: 'coat' },
  { kana: 'スーツ', romanji: 'suutsu', meaning: 'suit' },
  { kana: 'ネクタイ', romanji: 'nekutai', meaning: 'necktie' },
  { kana: 'パンツ', romanji: 'pantsu', meaning: 'pants' },
  { kana: 'ジーンズ', romanji: 'jiinzu', meaning: 'jeans' },
  { kana: 'スカート', romanji: 'sukaato', meaning: 'skirt' },
  { kana: 'ドレス', romanji: 'doresu', meaning: 'dress' },
  { kana: 'シューズ', romanji: 'shuuzu', meaning: 'shoes' },
  { kana: 'スニーカー', romanji: 'suniikaa', meaning: 'sneakers' },
  { kana: 'ブーツ', romanji: 'buutsu', meaning: 'boots' },
  { kana: 'サンダル', romanji: 'sandaru', meaning: 'sandals' },
  { kana: 'ソックス', romanji: 'sokkusu', meaning: 'socks' },
  { kana: 'ベルト', romanji: 'beruto', meaning: 'belt' },
  { kana: 'バッグ', romanji: 'baggu', meaning: 'bag' },
  { kana: 'ハンドバッグ', romanji: 'handobaggu', meaning: 'handbag' },
  { kana: 'バックパック', romanji: 'bakkupakku', meaning: 'backpack' },
  { kana: 'ハット', romanji: 'hatto', meaning: 'hat' },
  { kana: 'キャップ', romanji: 'kyappu', meaning: 'cap' },
  { kana: 'スカーフ', romanji: 'sukaafu', meaning: 'scarf' },
  { kana: 'グローブ', romanji: 'guroobu', meaning: 'gloves' },
  { kana: 'ウォッチ', romanji: 'wocchi', meaning: 'watch' },
  { kana: 'メガネ', romanji: 'megane', meaning: 'glasses' },
  { kana: 'サングラス', romanji: 'sangurasu', meaning: 'sunglasses' },
  { kana: 'アクセサリー', romanji: 'akusesarii', meaning: 'accessory' },
  { kana: 'ネックレス', romanji: 'nekkuresu', meaning: 'necklace' },
  { kana: 'リング', romanji: 'ringu', meaning: 'ring' },
  { kana: 'ブレスレット', romanji: 'buresuretto', meaning: 'bracelet' },
  { kana: 'イヤリング', romanji: 'iyaringu', meaning: 'earrings' },
  { kana: 'ファッション', romanji: 'fasshon', meaning: 'fashion' },
  { kana: 'スタイル', romanji: 'sutairu', meaning: 'style' },
  { kana: 'トレンド', romanji: 'torendo', meaning: 'trend' },
  { kana: 'ブランド', romanji: 'burando', meaning: 'brand' },
  { kana: 'デザイナー', romanji: 'dezainaa', meaning: 'designer' },
  { kana: 'モデル', romanji: 'moderu', meaning: 'model' },

  // Home & Kitchen
  { kana: 'ドア', romanji: 'doa', meaning: 'door' },
  { kana: 'ウィンドウ', romanji: 'windou', meaning: 'window' },
  { kana: 'カーテン', romanji: 'kaaten', meaning: 'curtain' },
  { kana: 'カーペット', romanji: 'kaapetto', meaning: 'carpet' },
  { kana: 'ラグ', romanji: 'ragu', meaning: 'rug' },
  { kana: 'ミラー', romanji: 'miraa', meaning: 'mirror' },
  { kana: 'ランプ', romanji: 'ranpu', meaning: 'lamp' },
  { kana: 'ライト', romanji: 'raito', meaning: 'light' },
  { kana: 'ファン', romanji: 'fan', meaning: 'fan' },
  { kana: 'ヒーター', romanji: 'hiitaa', meaning: 'heater' },
  { kana: 'エアコン', romanji: 'eakon', meaning: 'air conditioner' },
  { kana: 'レフリジェレーター', romanji: 'refurijereetaa', meaning: 'refrigerator' },
  { kana: 'マイクロウェーブ', romanji: 'maikuroweeb', meaning: 'microwave' },
  { kana: 'オーブン', romanji: 'oobun', meaning: 'oven' },
  { kana: 'トースター', romanji: 'toosutaa', meaning: 'toaster' },
  { kana: 'ブレンダー', romanji: 'burendaa', meaning: 'blender' },
  { kana: 'ミキサー', romanji: 'mikisaa', meaning: 'mixer' },
  { kana: 'ケトル', romanji: 'ketoru', meaning: 'kettle' },
  { kana: 'ポット', romanji: 'potto', meaning: 'pot' },
  { kana: 'パン', romanji: 'pan', meaning: 'pan' },
  { kana: 'ディッシュ', romanji: 'disshu', meaning: 'dish' },
  { kana: 'プレート', romanji: 'pureeto', meaning: 'plate' },
  { kana: 'ボウル', romanji: 'bouru', meaning: 'bowl' },
  { kana: 'カップ', romanji: 'kappu', meaning: 'cup' },
  { kana: 'グラス', romanji: 'gurasu', meaning: 'glass' },
  { kana: 'スプーン', romanji: 'supuun', meaning: 'spoon' },
  { kana: 'フォーク', romanji: 'fooku', meaning: 'fork' },
  { kana: 'ナイフ', romanji: 'naifu', meaning: 'knife' },
  { kana: 'タオル', romanji: 'taoru', meaning: 'towel' },
  { kana: 'ソープ', romanji: 'soopu', meaning: 'soap' },
  { kana: 'シャンプー', romanji: 'shanpuu', meaning: 'shampoo' },

  // Countries & Cities
  { kana: 'アメリカ', romanji: 'amerika', meaning: 'America' },
  { kana: 'カナダ', romanji: 'kanada', meaning: 'Canada' },
  { kana: 'メキシコ', romanji: 'mekishiko', meaning: 'Mexico' },
  { kana: 'ブラジル', romanji: 'burajiru', meaning: 'Brazil' },
  { kana: 'イギリス', romanji: 'igirisu', meaning: 'England, UK' },
  { kana: 'フランス', romanji: 'furansu', meaning: 'France' },
  { kana: 'ドイツ', romanji: 'doitsu', meaning: 'Germany' },
  { kana: 'イタリア', romanji: 'itaria', meaning: 'Italy' },
  { kana: 'スペイン', romanji: 'supein', meaning: 'Spain' },
  { kana: 'ロシア', romanji: 'roshia', meaning: 'Russia' },
  { kana: 'チャイナ', romanji: 'chaina', meaning: 'China' },
  { kana: 'コリア', romanji: 'koria', meaning: 'Korea' },
  { kana: 'インド', romanji: 'indo', meaning: 'India' },
  { kana: 'オーストラリア', romanji: 'oosutoraria', meaning: 'Australia' },
  { kana: 'アフリカ', romanji: 'afurika', meaning: 'Africa' },
  { kana: 'アジア', romanji: 'ajia', meaning: 'Asia' },
  { kana: 'ヨーロッパ', romanji: 'yooroppa', meaning: 'Europe' },
  { kana: 'トーキョー', romanji: 'tookyoo', meaning: 'Tokyo' },
  { kana: 'パリ', romanji: 'pari', meaning: 'Paris' },
  { kana: 'ロンドン', romanji: 'rondon', meaning: 'London' },
  { kana: 'ニューヨーク', romanji: 'nyuuyooku', meaning: 'New York' },
  { kana: 'ローマ', romanji: 'rooma', meaning: 'Rome' },

  // Miscellaneous
  { kana: 'メニュー', romanji: 'menyuu', meaning: 'menu' },
  { kana: 'サービス', romanji: 'saabisu', meaning: 'service' },
  { kana: 'プライス', romanji: 'puraisu', meaning: 'price' },
  { kana: 'セール', romanji: 'seeru', meaning: 'sale' },
  { kana: 'ディスカウント', romanji: 'disukaunto', meaning: 'discount' },
  { kana: 'フリー', romanji: 'furii', meaning: 'free' },
  { kana: 'プレミアム', romanji: 'puremiamu', meaning: 'premium' },
  { kana: 'ボーナス', romanji: 'boonasu', meaning: 'bonus' },
  { kana: 'ポイント', romanji: 'pointo', meaning: 'point' },
  { kana: 'カード', romanji: 'kaado', meaning: 'card' },
  { kana: 'チケット', romanji: 'chiketto', meaning: 'ticket' },
  { kana: 'パスポート', romanji: 'pasupooto', meaning: 'passport' },
  { kana: 'ビザ', romanji: 'biza', meaning: 'visa' },
  { kana: 'ツアー', romanji: 'tsuaa', meaning: 'tour' },
  { kana: 'ガイド', romanji: 'gaido', meaning: 'guide' },
  { kana: 'スーベニア', romanji: 'suubenia', meaning: 'souvenir' },
  { kana: 'ギフト', romanji: 'gifuto', meaning: 'gift' },
  { kana: 'プレゼント', romanji: 'purezento', meaning: 'present' },
  { kana: 'パーティー', romanji: 'paatii', meaning: 'party' },
  { kana: 'イベント', romanji: 'ibento', meaning: 'event' },
  { kana: 'フェスティバル', romanji: 'fesutibaru', meaning: 'festival' },
  { kana: 'クリスマス', romanji: 'kurisumasu', meaning: 'Christmas' },
  { kana: 'ハロウィン', romanji: 'harowin', meaning: 'Halloween' },
  { kana: 'バレンタイン', romanji: 'barentain', meaning: 'Valentine' },
  { kana: 'バースデー', romanji: 'baasudee', meaning: 'birthday' },
  { kana: 'メッセージ', romanji: 'messeeji', meaning: 'message' },
  { kana: 'コメント', romanji: 'komento', meaning: 'comment' },
  { kana: 'ライク', romanji: 'raiku', meaning: 'like' },
  { kana: 'シェア', romanji: 'shea', meaning: 'share' },
  { kana: 'フォロー', romanji: 'foroo', meaning: 'follow' },
  { kana: 'メンバー', romanji: 'menbaa', meaning: 'member' },
  { kana: 'ユーザー', romanji: 'yuuzaa', meaning: 'user' },
  { kana: 'アカウント', romanji: 'akaunto', meaning: 'account' },
  { kana: 'パスワード', romanji: 'pasuwaado', meaning: 'password' },
  { kana: 'ログイン', romanji: 'roguin', meaning: 'login' },
  { kana: 'プロフィール', romanji: 'purofuuru', meaning: 'profile' },
  { kana: 'セッティング', romanji: 'settingu', meaning: 'setting' },
  { kana: 'オプション', romanji: 'opushon', meaning: 'option' },
  { kana: 'レベル', romanji: 'reberu', meaning: 'level' },
  { kana: 'ランク', romanji: 'ranku', meaning: 'rank' },
];

export function getRandomWord(type: 'hiragana' | 'katakana' | 'mix'): Word {
  let pool: Word[] = [];

  if (type === 'hiragana') {
    pool = hiraganaWords;
  } else if (type === 'katakana') {
    pool = katakanaWords;
  } else {
    pool = [...hiraganaWords, ...katakanaWords];
  }

  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex];
}
